/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlbumRouteImport } from './routes/_authenticated/album'
import { Route as AuthenticatedTrocasIndexRouteImport } from './routes/_authenticated/trocas.index'
import { Route as AuthenticatedTrocasNovaRouteImport } from './routes/_authenticated/trocas.nova'
import { Route as AuthenticatedTrocasIdRouteImport } from './routes/_authenticated/trocas.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlbumRoute = AuthenticatedAlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocasIndexRoute =
  AuthenticatedTrocasIndexRouteImport.update({
    id: '/trocas/',
    path: '/trocas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrocasNovaRoute = AuthenticatedTrocasNovaRouteImport.update({
  id: '/trocas/nova',
  path: '/trocas/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocasIdRoute = AuthenticatedTrocasIdRouteImport.update({
  id: '/trocas/$id',
  path: '/trocas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/album': typeof AuthenticatedAlbumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/trocas/$id': typeof AuthenticatedTrocasIdRoute
  '/trocas/nova': typeof AuthenticatedTrocasNovaRoute
  '/trocas/': typeof AuthenticatedTrocasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/album': typeof AuthenticatedAlbumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/trocas/$id': typeof AuthenticatedTrocasIdRoute
  '/trocas/nova': typeof AuthenticatedTrocasNovaRoute
  '/trocas': typeof AuthenticatedTrocasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/album': typeof AuthenticatedAlbumRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/trocas/$id': typeof AuthenticatedTrocasIdRoute
  '/_authenticated/trocas/nova': typeof AuthenticatedTrocasNovaRoute
  '/_authenticated/trocas/': typeof AuthenticatedTrocasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/album'
    | '/dashboard'
    | '/trocas/$id'
    | '/trocas/nova'
    | '/trocas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/album'
    | '/dashboard'
    | '/trocas/$id'
    | '/trocas/nova'
    | '/trocas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/album'
    | '/_authenticated/dashboard'
    | '/_authenticated/trocas/$id'
    | '/_authenticated/trocas/nova'
    | '/_authenticated/trocas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/album': {
      id: '/_authenticated/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AuthenticatedAlbumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocas/': {
      id: '/_authenticated/trocas/'
      path: '/trocas'
      fullPath: '/trocas/'
      preLoaderRoute: typeof AuthenticatedTrocasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocas/nova': {
      id: '/_authenticated/trocas/nova'
      path: '/trocas/nova'
      fullPath: '/trocas/nova'
      preLoaderRoute: typeof AuthenticatedTrocasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocas/$id': {
      id: '/_authenticated/trocas/$id'
      path: '/trocas/$id'
      fullPath: '/trocas/$id'
      preLoaderRoute: typeof AuthenticatedTrocasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlbumRoute: typeof AuthenticatedAlbumRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTrocasIdRoute: typeof AuthenticatedTrocasIdRoute
  AuthenticatedTrocasNovaRoute: typeof AuthenticatedTrocasNovaRoute
  AuthenticatedTrocasIndexRoute: typeof AuthenticatedTrocasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlbumRoute: AuthenticatedAlbumRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTrocasIdRoute: AuthenticatedTrocasIdRoute,
  AuthenticatedTrocasNovaRoute: AuthenticatedTrocasNovaRoute,
  AuthenticatedTrocasIndexRoute: AuthenticatedTrocasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
